package dev.blazelight.p4oc.ui.theme.opencode

import androidx.compose.ui.graphics.Color

fun createFallbackTheme(isDark: Boolean): OpenCodeTheme {
    return if (isDark) {
        OpenCodeTheme(
            name = "catppuccin",
            isDark = true,
            primary = Color(0xFF89B4FA),
            secondary = Color(0xFFCBA6F7),
            accent = Color(0xFFF5C2E7),
            text = Color(0xFFCDD6F4),
            textMuted = Color(0xFFBAC2DE),
            background = Color(0xFF1E1E2E),
            error = Color(0xFFF38BA8),
            warning = Color(0xFFF9E2AF),
            success = Color(0xFFA6E3A1),
            info = Color(0xFF94E2D5),
            backgroundPanel = Color(0xFF181825),
            backgroundElement = Color(0xFF11111B),
            border = Color(0xFF313244),
            borderActive = Color(0xFF45475A),
            borderSubtle = Color(0xFF585B70),
            diffAdded = Color(0xFFA6E3A1),
            diffRemoved = Color(0xFFF38BA8),
            diffContext = Color(0xFF9399B2),
            diffHunkHeader = Color(0xFFFAB387),
            diffHighlightAdded = Color(0xFFA6E3A1),
            diffHighlightRemoved = Color(0xFFF38BA8),
            diffAddedBg = Color(0xFF24312B),
            diffRemovedBg = Color(0xFF3C2A32),
            diffContextBg = Color(0xFF181825),
            diffLineNumber = Color(0xFF45475A),
            diffAddedLineNumberBg = Color(0xFF1E2A25),
            diffRemovedLineNumberBg = Color(0xFF32232A),
            markdownText = Color(0xFFCDD6F4),
            markdownHeading = Color(0xFFCBA6F7),
            markdownLink = Color(0xFF89B4FA),
            markdownLinkText = Color(0xFF89DCEB),
            markdownCode = Color(0xFFA6E3A1),
            markdownBlockQuote = Color(0xFFF9E2AF),
            markdownEmph = Color(0xFFF9E2AF),
            markdownStrong = Color(0xFFFAB387),
            markdownHorizontalRule = Color(0xFFA6ADC8),
            markdownListItem = Color(0xFF89B4FA),
            markdownListEnumeration = Color(0xFF89DCEB),
            markdownImage = Color(0xFF89B4FA),
            markdownImageText = Color(0xFF89DCEB),
            markdownCodeBlock = Color(0xFFCDD6F4),
            syntaxComment = Color(0xFF9399B2),
            syntaxKeyword = Color(0xFFCBA6F7),
            syntaxFunction = Color(0xFF89B4FA),
            syntaxVariable = Color(0xFFF38BA8),
            syntaxString = Color(0xFFA6E3A1),
            syntaxNumber = Color(0xFFFAB387),
            syntaxType = Color(0xFFF9E2AF),
            syntaxOperator = Color(0xFF89DCEB),
            syntaxPunctuation = Color(0xFFCDD6F4),
        )
    } else {
        OpenCodeTheme(
            name = "catppuccin",
            isDark = false,
            primary = Color(0xFF1E66F5),
            secondary = Color(0xFF8839EF),
            accent = Color(0xFFEA76CB),
            text = Color(0xFF4C4F69),
            textMuted = Color(0xFF5C5F77),
            background = Color(0xFFEFF1F5),
            error = Color(0xFFD20F39),
            warning = Color(0xFFDF8E1D),
            success = Color(0xFF40A02B),
            info = Color(0xFF179299),
            backgroundPanel = Color(0xFFE6E9EF),
            backgroundElement = Color(0xFFDCE0E8),
            border = Color(0xFFCCD0DA),
            borderActive = Color(0xFFBCC0CC),
            borderSubtle = Color(0xFFACB0BE),
            diffAdded = Color(0xFF40A02B),
            diffRemoved = Color(0xFFD20F39),
            diffContext = Color(0xFF7C7F93),
            diffHunkHeader = Color(0xFFFE640B),
            diffHighlightAdded = Color(0xFF40A02B),
            diffHighlightRemoved = Color(0xFFD20F39),
            diffAddedBg = Color(0xFFD6F0D9),
            diffRemovedBg = Color(0xFFF6DFE2),
            diffContextBg = Color(0xFFE6E9EF),
            diffLineNumber = Color(0xFFBCC0CC),
            diffAddedLineNumberBg = Color(0xFFC9E3CB),
            diffRemovedLineNumberBg = Color(0xFFE9D3D6),
            markdownText = Color(0xFF4C4F69),
            markdownHeading = Color(0xFF8839EF),
            markdownLink = Color(0xFF1E66F5),
            markdownLinkText = Color(0xFF04A5E5),
            markdownCode = Color(0xFF40A02B),
            markdownBlockQuote = Color(0xFFDF8E1D),
            markdownEmph = Color(0xFFDF8E1D),
            markdownStrong = Color(0xFFFE640B),
            markdownHorizontalRule = Color(0xFF6C6F85),
            markdownListItem = Color(0xFF1E66F5),
            markdownListEnumeration = Color(0xFF04A5E5),
            markdownImage = Color(0xFF1E66F5),
            markdownImageText = Color(0xFF04A5E5),
            markdownCodeBlock = Color(0xFF4C4F69),
            syntaxComment = Color(0xFF7C7F93),
            syntaxKeyword = Color(0xFF8839EF),
            syntaxFunction = Color(0xFF1E66F5),
            syntaxVariable = Color(0xFFD20F39),
            syntaxString = Color(0xFF40A02B),
            syntaxNumber = Color(0xFFFE640B),
            syntaxType = Color(0xFFDF8E1D),
            syntaxOperator = Color(0xFF04A5E5),
            syntaxPunctuation = Color(0xFF4C4F69),
        )
    }
}
